name: Action

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

defaults:
    run:
        shell: bash

jobs:
    build_and_test:
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
                include:
                  - os: windows-latest
                    bin: QTranslatorTests.exe
                    dir: Debug
                  - os: ubuntu-latest
                    bin: QTranslatorTests
                    dir: .
                  - os: macos-latest
                    bin: QTranslatorTests
                    dir: .

        name: CI
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2

            - name: Install Required Dependencies on Ubuntu
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                sudo apt update
                sudo apt install -y g++-11
                sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11

            - name: Install Python Dependencies
              run: pip install qiskit

            - name: Build Project
              run: |
                cmake . -B build/ -DCMAKE_BUILD_TYPE=Debug
                cmake --build build/

            - name: Build Tests
              run: |
                cmake . -B build_tests/ -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON
                cmake --build build_tests/

            - name: Run Tests
              working-directory: ${{ matrix.dir }}
              run: ./${{ matrix.bin }}